# Default values for backend.

replicaCount: 1

image:
  repository: gitlab.praktikum-services.ru:5050/std-024-07/momo-store/momo-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

dockerconfig: ""

service:
  type: ClusterIP
  port: 8081

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 2048Mi

autoscaling:
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
    # targetMemoryUtilizationPercentage: 75