# Default values for frontend.

replicaCount: 1

image:
  repository: gitlab.praktikum-services.ru:5050/std-024-07/momo-store/momo-frontend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

dockerconfig: ""

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi

autoscaling:
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 75
    # targetMemoryUtilizationPercentage: 75

upstream:
  host: localhost
  port: "8081"

ingress:
  enabled: true
  annotations: {}
  className: "nginx"
  hosts:
    - momo-store.glebfedotov.ru
  paths:
    - /
  pathType: ImplementationSpecific
  tls: 
    - hosts:
        - momo-store.glebfedotov.ru
      secretName: momo-store
