apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "frontend.name" . }}
  name: momo-store
  namespace: default
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "frontend.name" . }}
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer