apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: momo-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: momo-frontend
    argocd.argoproj.io/instance: momo-store
  name: momo-store
  namespace: default
spec:
  selector:
    app.kubernetes.io/instance: momo-store
    app.kubernetes.io/name: momo-frontend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer