{{- if .Values.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "backend.fullname" . }}
  minReplicas: {{ .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.maxReplicas }}
#  metrics:
#    {{- if .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Value
#          value: {{ .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
#    {{- end }}
#    {{- if .Values.autoscaling.hpa.targetMemoryUtilizationPercentage }}
#    - type: Resource
#      resource:
#        name: memory
#        target: 
#          type: Value
#          value: {{ .Values.autoscaling.hpa.targetMemoryUtilizationPercentage }}
#    {{- end }}
{{- end }}
